name: Generate commit per dayweek

on:
  schedule:
    # runs at 6 AM BRT (São Paulo Time)
    - cron: "0 9 * * *"
  workflow_dispatch:
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
      WAKATIME_API_KEY:
        required: true
jobs:
  update-readme:
    name: Updated commit-dayweek metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run GitHub Stats Action
        uses: thanhhaudev/github-stats@master
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token, required
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_METRICS: "COMMIT_DAYS_OF_WEEK" # show metrics, separated by comma
          WAKATIME_DATA: "" # show data, separated by comma
          SECTION_NAME: commit-dayweek
          WAKATIME_RANGE: all_time
          TIME_ZONE: America/Sao_Paulo
          ONLY_MAIN_BRANCH: "true" # only fetch data from the main branch
          EXCLUDE_FORK_REPOS: "true"
          SHOW_LAST_UPDATE: "false" # show last update time
          PROGRESS_BAR_VERSION: 1
          COMMIT_MESSAGE: Updated commit-dayweek metrics
          COMMIT_USER_NAME: LucasKazuhiro
          COMMIT_USER_EMAIL: lucaslko429@gmail.com