name: Main Workflow Runner

on:
  workflow_dispatch:
  schedule:
    # runs at 6 AM BRT (São Paulo Time)
    - cron: "0 9 * * *"

jobs:
  call-commit-day-moment:
    uses: ./.github/workflows/commit-day-moment.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


  call-commit-dayweek:
    needs: call-commit-day-moment
    if: always()
    uses: ./.github/workflows/commit-dayweek.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


  call-editor-time:
    needs: call-commit-dayweek
    if: always()
    uses: ./.github/workflows/editor-time.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


  call-lang-time:
    needs: call-editor-time
    if: always()
    uses: ./.github/workflows/lang-time.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


  call-stats-transparent:
    needs: call-lang-time
    if: always()
    uses: ./.github/workflows/stats-transparent.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}