name: Main Workflow Runner

on:
  workflow_dispatch:
  schedule:
    # runs at 6 AM BRT (São Paulo Time)
    - cron: "0 9 * * *"

jobs:
  call-commit-day-moment:
    uses: LucasKazuhiro/LucasKazuhiro/.github/workflows/commit-day-moment.yml@main


  call-commit-dayweek:
    needs: call-commit-day-moment
    if: always()
    uses: .github/workflows/commit-dayweek.yml@main


  call-editor-time:
    needs: call-commit-dayweek
    if: always()
    uses: .github/workflows/editor-time.yml@main


  call-lang-time:
    needs: call-editor-time
    if: always()
    uses: .github/workflows/lang-time.yml@main


  call-stats-transparent:
    needs: call-lang-time
    if: always()
    uses: .github/workflows/stats-transparent.yml@main