name: WakaTime generate langAllTimeHours

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM BRT (São Paulo Time)
    - cron: "0 3 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: langAllTimeHours
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          CODE_LANG: rust
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          # SHOW_MASKED_TIME: false
          # STOP_AT_OTHER: true
          IGNORED_LANGUAGES: Binary YAML JSON TOML Properties "Java Properties" Git "GitIgnore file" "Git Config"
          COMMIT_MESSAGE: Updated "langAllTimeHours" metrics
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Lucas Kazuhiro Okokama
          AUTHOR_EMAIL: lucaslko429@gmail.com
